### ISSUE TITLE
"float_equal" was not  in this scope

### ISSUE THREAD

**Issue by vchuravy** [Morwenn/static_math#1]
When compiling a project using static_math using gcc and c++14 enable I get the following error:

````
static_math/include/static_math/cmath.inl: In instantiation of ‘constexpr decltype (std::sqrt(x)) smath::details::sqrt_helper(T, T) [with T = double; decltype (std::sqrt(x)) = double]’:
static_math/include/static_math/cmath.inl:141:32:   required from ‘constexpr decltype (std::sqrt(x)) smath::sqrt(Float) [with Float = double; <template-parameter-1-2> = void; decltype (std::sqrt(x)) = double]’
globals.hpp:29:56:   required from here
static_math/include/static_math/cmath.inl:38:27: error: ‘float_equal’ was not declared in this scope
         return float_equal(x, y*y) ? y :
````

**Comment by vchuravy** [comment]
Replacing [1] by `equals` compiles
https://github.com/Morwenn/static_math/blob/0399334aa8dcc9d25d9e64c632bed25716d954c4/include/static_math/cmath.inl#L38

**Comment by Morwenn** [comment]
Right, I probably dragged the implementation from another of my libraries and forgot to change the name. I will fix it this weekend (I don't have access to my codebase right now). Thanks!
