### ISSUE TITLE
sqrt segfaults for some input

### ISSUE THREAD

**Issue by namark** [Morwenn/static_math#25]
The following code example causes a segmentation fault after a few iterations
```
auto random = std::mt19937_64{std::random_device{}()};
auto number = std::uniform_real_distribution<float>{};
for(int i = 0; i < 10'000'000; ++i)
	smath::sqrt( number(random) );
```

It seems that the Babylonian algorithm goes infinite for some specific numbers, because it can never satisfy the is_close condition.

Using a condition like this instead seems to fix the problem,
```
std::abs(a - b) <= std::numeric_limits<T>::epsilon() * std::abs(a + b);
```
but I have no idea why or how, it's just something I found [here](https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon).

**Comment by Morwenn** [comment]
Interesting, I'll try to have a look tonight and to fix it, thanks for reporting.

**Comment by namark** [comment]
Sure, here are a few literals that do it for me.
```
4.916330874e-01F
3.804553151e-01F
4.505589902e-01F
3.162864149e-01F
4.889709353e-01F
```

**Comment by Morwenn** [comment]
Apparently I've got more issues of tests that don't compile anymore with the more recent compilers, I'll have to look at this further this week.

**Comment by Morwenn** [comment]
I added your tests, changed the formula to the one from cppreference and everything seems to compile. Thanks for the report :)

Too many things seem broken with new compilers though (I'm using GCC 9.2 and `exp` doesn't work), I guess that I will need to complete the continuous integration and open bug reports accordingly.
